// This file was generated by running: `bun run generate-typebox-types.ts`
//
// The only modification was to reorder the declarations since
// they are produced in a the wrong order.

import { Type, type Static } from '@sinclair/typebox'

export type FilesOptions = Static<typeof FilesOptions>
export const FilesOptions = Type.Union([Type.Literal('none'), Type.Literal('one'), Type.Literal('many')])

export type ApiModels = Static<typeof ApiModels>
export const ApiModels = Type.Array(Type.Tuple([Type.String(), Type.Any()]))

export type ApiInfo = Static<typeof ApiInfo>
export const ApiInfo = Type.Object({
    name: Type.String(),
    description: Type.String(),
    version: Type.String(),
    url: Type.String(),
})

export type Endpoint = Static<typeof Endpoint>
export const Endpoint = Type.Object({
    status: Type.Optional(Type.String()),
    name: Type.String(),
    summary: Type.Optional(Type.String()),
    description: Type.Optional(Type.String()),
    actor: Type.Optional(Type.String()),
    input: Type.Any(),
    output: Type.Any(),
    ifiles: Type.Optional(FilesOptions),
    ofiles: Type.Optional(FilesOptions),
    clientTtl: Type.Optional(Type.Number()),
})

export type Module = Static<typeof Module>
export const Module = Type.Recursive((This) =>
    Type.Object({
        name: Type.String(),
        description: Type.Optional(Type.String()),
        hideFromDoc: Type.Optional(Type.Boolean()),
        endpoints: Type.Array(Endpoint),
        submodules: Type.Array(This),
    }),
)

export type ApiDir = Static<typeof ApiDir>
export const ApiDir = Type.Object({
    info: ApiInfo,
    root: Module,
    models: ApiModels,
})
