import { Command, type CommandUnknownOpts, type Option } from '@commander-js/extra-typings'
import { exists, mkdir, readFile, writeFile, rm } from 'fs/promises'
import { homedir } from 'os'
import { join } from 'path'
import { paths } from './settings'
import { printStdout } from './print'

// Enable debug logging by uncommenting the line below
const DEBUG = false
const _log = (msg: string) => {
    if (DEBUG) process.stderr.write(`[completions] ${msg}\n`)
}

// ============================================================================
// Shell completion scripts (embedded for distribution)
// ============================================================================

const BASH_COMPLETION_SCRIPT = `# Bash completion for jutge CLI
# Auto-generated by: jutge completions install

_complete_jutge_bash() {
    local index=$((COMP_CWORD + 1))
    local words="\${COMP_WORDS[*]}"
    local IFS=$'\\n'
    local completions=($(jutge completions "\$index" "\$words" 2>/dev/null))
    COMPREPLY=($(compgen -W "\${completions[*]}" -- "\${COMP_WORDS[COMP_CWORD]}"))
}

complete -F _complete_jutge_bash jutge
`

const ZSH_COMPLETION_SCRIPT = `# Zsh completion for jutge CLI
# Auto-generated by: jutge completions install

_complete_jutge_zsh() {
    local word_string="\${words[*]}"
    local completions=(\${(f)"$(jutge completions "$CURRENT" "$word_string" 2>/dev/null)"})
    compadd -- "\${completions[@]}"
}

autoload -Uz compinit
compinit -u
compdef _complete_jutge_zsh jutge
`

// ============================================================================
// Shell detection and RC file paths
// ============================================================================

type ShellType = 'bash' | 'zsh' | 'unknown'

interface ShellInfo {
    type: ShellType
    rcFile: string
    completionFile: string
    script: string
}

function detectShell(): ShellInfo {
    const shell = process.env.SHELL || ''
    const shellName = shell.split('/').pop() || ''

    const completionsDir = join(paths.data, 'completions')

    if (shellName === 'zsh' || process.env.ZSH_VERSION) {
        return {
            type: 'zsh',
            rcFile: join(homedir(), '.zshrc'),
            completionFile: join(completionsDir, 'jutge.zsh'),
            script: ZSH_COMPLETION_SCRIPT,
        }
    } else if (shellName === 'bash' || process.env.BASH_VERSION) {
        return {
            type: 'bash',
            rcFile: join(homedir(), '.bashrc'),
            completionFile: join(completionsDir, 'jutge.bash'),
            script: BASH_COMPLETION_SCRIPT,
        }
    }

    return {
        type: 'unknown',
        rcFile: '',
        completionFile: '',
        script: '',
    }
}

const SOURCE_LINE_MARKER = '# jutge-cli completions'

function getSourceLine(completionFile: string): string {
    return `${SOURCE_LINE_MARKER}\nsource "${completionFile}"\n`
}

async function isCompletionInstalled(rcFile: string): Promise<boolean> {
    try {
        const content = await readFile(rcFile, 'utf8')
        return content.includes(SOURCE_LINE_MARKER)
    } catch {
        return false
    }
}

async function installCompletions(): Promise<void> {
    const shell = detectShell()

    if (shell.type === 'unknown') {
        printStdout('Could not detect your shell. Supported shells: bash, zsh')
        printStdout(`SHELL environment variable: ${process.env.SHELL || '(not set)'}`)
        return
    }

    printStdout(`Detected shell: ${shell.type}`)

    // Create completions directory
    const completionsDir = join(paths.data, 'completions')
    await mkdir(completionsDir, { recursive: true })

    // Write the completion script
    await writeFile(shell.completionFile, shell.script)
    printStdout(`Wrote completion script to: ${shell.completionFile}`)

    // Check if already installed in rc file
    if (await isCompletionInstalled(shell.rcFile)) {
        printStdout(`Completions already configured in ${shell.rcFile}`)
        return
    }

    // Add source line to rc file
    const sourceLine = getSourceLine(shell.completionFile)

    // Read existing content (or empty string if file doesn't exist)
    let rcContent = ''
    try {
        rcContent = await readFile(shell.rcFile, 'utf8')
    } catch {
        // File doesn't exist, that's fine
    }

    // Ensure there's a newline before our addition
    if (rcContent && !rcContent.endsWith('\n')) {
        rcContent += '\n'
    }

    // Append the source line
    rcContent += `\n${sourceLine}`
    await writeFile(shell.rcFile, rcContent)

    printStdout(`Added completion source to: ${shell.rcFile}`)
    printStdout('')
    printStdout(`Shell completions installed successfully!`)
    printStdout(`Restart your shell or run: source ${shell.rcFile}`)
}

async function uninstallCompletions(): Promise<void> {
    const shell = detectShell()

    if (shell.type === 'unknown') {
        printStdout('Could not detect your shell. Supported shells: bash, zsh')
        return
    }

    printStdout(`Detected shell: ${shell.type}`)

    // Remove completion script file
    if (await exists(shell.completionFile)) {
        await rm(shell.completionFile)
        printStdout(`Removed: ${shell.completionFile}`)
    }

    // Remove source line from rc file
    if (await exists(shell.rcFile)) {
        const content = await readFile(shell.rcFile, 'utf8')
        const lines = content.split('\n')

        // Filter out the marker line and the source line that follows it
        const newLines: string[] = []
        let skipNext = false
        for (const line of lines) {
            if (skipNext) {
                skipNext = false
                continue
            }
            if (line.trim() === SOURCE_LINE_MARKER) {
                skipNext = true
                continue
            }
            newLines.push(line)
        }

        // Remove extra blank lines at the end
        while (newLines.length > 0 && newLines[newLines.length - 1]?.trim() === '') {
            newLines.pop()
        }

        const newContent = newLines.join('\n') + '\n'
        await writeFile(shell.rcFile, newContent)
        printStdout(`Removed completion source from: ${shell.rcFile}`)
    }

    printStdout('')
    printStdout('Shell completions uninstalled successfully!')
    printStdout(`Restart your shell or run: source ${shell.rcFile}`)
}

async function showCompletionsStatus(): Promise<void> {
    const shell = detectShell()

    printStdout(`Shell: ${shell.type === 'unknown' ? 'unknown' : shell.type}`)
    printStdout(`SHELL env: ${process.env.SHELL || '(not set)'}`)

    if (shell.type === 'unknown') {
        return
    }

    printStdout(`RC file: ${shell.rcFile}`)
    printStdout(`Completion file: ${shell.completionFile}`)

    const fileExists = await exists(shell.completionFile)
    const rcConfigured = await isCompletionInstalled(shell.rcFile)

    printStdout('')
    printStdout(`Completion file exists: ${fileExists ? 'yes' : 'no'}`)
    printStdout(`RC file configured: ${rcConfigured ? 'yes' : 'no'}`)
    printStdout('')

    if (fileExists && rcConfigured) {
        printStdout('Status: Completions are installed and configured.')
    } else if (!fileExists && !rcConfigured) {
        printStdout('Status: Completions are not installed.')
        printStdout('Run: jutge completions install')
    } else {
        printStdout('Status: Partial installation detected.')
        printStdout('Run: jutge completions uninstall && jutge completions install')
    }
}

// ============================================================================
// Completion generation logic (called by shell scripts)
// ============================================================================

/**
 * Check if an option expects a value (has an argument)
 */
const optionExpectsValue = (option: Option): boolean => {
    return option.flags.includes('<') || option.flags.includes('[')
}

/**
 * Find an option in a command by its short or long flag
 */
const findOption = (cmd: CommandUnknownOpts, flag: string): Option | undefined => {
    return cmd.options.find((opt) => opt.short === flag || opt.long === flag)
}

/**
 * Check if a command is hidden (should not appear in completions)
 */
const isHiddenCommand = (cmd: CommandUnknownOpts): boolean => {
    return (cmd as any)._hidden === true
}

/**
 * Compute available completions for the current cursor position
 */
const computeAvailableOptions = (index: number, words: string[], jutgeCmd: Command): string[] => {
    _log(`computeAvailableOptions(index=${index}, words=${JSON.stringify(words)})`)

    // Navigate to the current command based on the words before the cursor
    let currCmd: CommandUnknownOpts = jutgeCmd
    let k = 1 // Start at 1 to skip the program name ('jutge')

    while (k < index) {
        const word = words[k]
        _log(`k=${k}, cmd='${currCmd.name()}', word='${word}'`)

        if (!word) {
            _log(`Empty word at position ${k}, stopping navigation`)
            break
        }

        // Check if this word is an option
        if (word.startsWith('-')) {
            const option = findOption(currCmd, word)
            if (option && optionExpectsValue(option)) {
                // Skip the next word (the option's value)
                k += 2
                _log(`Option ${word} expects value, skipping to k=${k}`)
                continue
            }
            // Boolean option or unknown option, just skip it
            k++
            continue
        }

        // Try to find a subcommand with this name
        const foundCmd = currCmd.commands.find((c) => c.name() === word && !isHiddenCommand(c))
        if (foundCmd) {
            _log(`Found subcommand '${foundCmd.name()}'`)
            currCmd = foundCmd
            k++
            continue
        }

        // Word is not a subcommand, could be an argument - stop navigating deeper
        _log(`'${word}' is not a subcommand of '${currCmd.name()}', treating as argument`)
        k++
    }

    _log(`Finished navigation at cmd='${currCmd.name()}', k=${k}`)

    // Check if we're completing after an option that expects a value
    const prevWord = words[index - 1]
    if (prevWord && prevWord.startsWith('-')) {
        const option = findOption(currCmd, prevWord)
        if (option && optionExpectsValue(option)) {
            _log(`Previous word '${prevWord}' expects a value, no suggestions`)
            return []
        }
    }

    // Get the current word being completed (might be partial)
    const currentWord = words[index] || ''
    _log(`Current word being completed: '${currentWord}'`)

    const result: string[] = []

    // Add matching subcommands (excluding hidden ones)
    for (const subcmd of currCmd.commands) {
        if (isHiddenCommand(subcmd)) continue
        if (subcmd.name().startsWith(currentWord)) {
            _log(`Adding subcommand: ${subcmd.name()}`)
            result.push(subcmd.name())
        }
    }

    // Add matching options (only if current word starts with '-' or is empty)
    if (currentWord === '' || currentWord.startsWith('-')) {
        // Collect already-used options to avoid suggesting them again
        const usedOptions = new Set<string>()
        for (let i = 1; i < index; i++) {
            const w = words[i]
            if (w && w.startsWith('-')) {
                usedOptions.add(w)
            }
        }

        for (const option of currCmd.options) {
            const isUsed =
                (option.long && usedOptions.has(option.long)) || (option.short && usedOptions.has(option.short))

            if (option.long && option.long.startsWith(currentWord) && !isUsed) {
                _log(`Adding option: ${option.long}`)
                result.push(option.long)
            }
            if (option.short && option.short.startsWith(currentWord) && !isUsed) {
                _log(`Adding option: ${option.short}`)
                result.push(option.short)
            }
        }
    }

    _log(`Result: ${JSON.stringify(result)}`)
    return result
}

function generateCompletions(indexStr: string, wordsStr: string, jutgeCmd: Command): void {
    const index = Number(indexStr) - 1
    if (Number.isNaN(index) || index < 0) {
        _log(`Invalid index: ${indexStr}`)
        return
    }

    const words = wordsStr.split(' ')
    _log(`Parsed: index=${index}, words=${JSON.stringify(words)}`)

    const completions = computeAvailableOptions(index, words, jutgeCmd)
    completions.sort()

    for (const completion of completions) {
        console.log(completion)
    }
}

// ============================================================================
// Command definition
// ============================================================================

export const shellCompletionsCmd = (jutgeCmd: Command) => {
    const cmd = new Command('completions')
        .description('Shell completion support')
        .helpCommand(false)

    // Subcommand: install
    cmd.command('install')
        .description('Install shell completions for the current shell')
        .action(async () => {
            await installCompletions()
        })

    // Subcommand: uninstall
    cmd.command('uninstall')
        .description('Remove shell completions')
        .action(async () => {
            await uninstallCompletions()
        })

    // Subcommand: status
    cmd.command('status')
        .description('Show shell completions installation status')
        .action(async () => {
            await showCompletionsStatus()
        })

    // Default action: generate completions (called by shell scripts)
    // This handles: jutge completions <index> <words>
    cmd.argument('[index]', 'Cursor position (1-based) - used by shell scripts')
        .argument('[words]', 'Command line words - used by shell scripts')
        .action((indexStr, wordsStr) => {
            // Only generate completions if both arguments are provided
            // and the first looks like a number (not a subcommand)
            if (indexStr && wordsStr && /^\d+$/.test(indexStr)) {
                generateCompletions(indexStr, wordsStr, jutgeCmd)
            }
        })

    return cmd
}
